# Generated by Django 3.1.5 on 2021-02-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210131_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='client.size'),
        ),
    ]
