# Generated by Django 3.1.5 on 2021-02-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210131_2245'),
        ('client', '0002_order_email'),
    ]

    operations = [
    ]
