# Generated by Django 3.1.5 on 2021-02-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210131_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
