# Generated by Django 3.1.5 on 2021-02-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_merge_20210202_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
